[programs.localnet]
pool = "BHfLU4UsBdxBZk56GjpGAXkzu8B7JdMitGa9A1VTMmva"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/onkery/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
