[package]
edition = "2018"
name = "solana-api-types"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
base64 = "0.12"
bincode = "1.3"
bs58 = "0.4"
generic-array = {version = "0.14.3", default-features = false, features = ["serde", "more_lengths"]}
reqwest = "0.11"
serde = {version = "^1.0", features = ["derive"]}
serde_bytes = "0.11"
serde_derive = "^1.0"
serde_json = "1.0"
thiserror = "1.0"
# zstd = {version = "0.5", features = ["wasm"]}
ruzstd = "0.2"

[dev-dependencies]
assert_matches = "1.3"
