[package]
name = "wasm-client"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
reqwest = "0.11"
serde = { version = "^1.0", features = ["derive"] }
serde_derive = "^1.0"
wasm-bindgen-futures = "0.4"
serde_json = "1.0"
wasm-bindgen = { version = "0.2", features = ["serde-serialize"]  }

# Это для подключения непосредственно web-sys.
# [dependencies.web-sys]
# version = "0.3"
# features = [
#   'Headers',
#   'Request',
#   'RequestInit',
#   'RequestMode',
#   'Response',
#   'Window',
# ]
