[package]
name = "solar"
version = "0.1.0"
edition = "2018"

[features]
sol-mem-intrinsics = []
test = ["solana-sdk"]

[dependencies]
solana-program = "1.7.2"
solana-sdk = { version = "1.7.2", optional = true }
static_assertions = "1.1.0"
itoap = "1.0.1"
byteorder = "1.4.3"
chrono = { version = "0.4.19", default-features = false }
strum = { version = "0.21", features = ["derive"] }
num-traits = "0.2.14"
borsh = "0.9.1"

[dev-dependencies]
solana-sdk = "1.7.2"