[package]
edition = "2018"
name = "solar"
version = "0.1.0"

[features]
sol-mem-intrinsics = []
test = ["solana-sdk", "solana-program"]
runtime-test = ["solana-program-test", "test"]
onchain = []

[dependencies]
az = "1.1.1"
borsh = "0.9.1"
byteorder = "1.4.3"
chrono = {version = "0.4.19", default-features = false}
fixed = {version = "1.9.0", features = ["num-traits"]}
itoap = "1.0.1"
lazy_static = "1.4"
minicbor = {version = "0.8.1", features = ["derive"]}
num-traits = "0.2.14"
parity-scale-codec = {version = "1.3.7", features = ["derive"]}
static_assertions = "1.1.0"
strum = {version = "0.21", features = ["derive"]}
async-trait = "0.1.51"
anyhow = "1.0.43"
serde = "1.0.127"
url = "2.2.2"

solar-macros = {path = "../solar-macros"}
solana-api-types = {path = "../solana-api-types"}

solana-sdk = {version = "1.7.2", optional = true}
solana-program = {version = "1.7.2", optional = true}
solana-program-test = {version = "1.7.2", optional = true}
anyhow = "1"


[dev-dependencies]
solana-sdk = "1.7.2"