[package]
name = "solar"
version = "0.1.0"
edition = "2018"

[features]
sol-mem-intrinsics = []
test = ["solana-sdk"]

[dependencies]
solana-program = "1.7.2"
solana-sdk = { version = "1.7.2", optional = true }
static_assertions = "1.1.0"
itoap = "1.0.1"
byteorder = "1.4.3"
chrono = { version = "0.4.19", default-features = false }
strum = { version = "0.21", features = ["derive"] }
num-traits = "0.2.14"
fixed = { version = "1.9.0", features = ["num-traits"] }
minicbor = { version = "0.8.1", features = ["derive"] }
az = "1.1.1"
borsh = "0.9.1"
parity-scale-codec = { version = "1.3.7", features = ["derive"] }


[dev-dependencies]
solana-sdk = "1.7.2"