name: CI

on: [push, pull_request]

jobs:
  build-test-wasm32:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-08-04
          target: wasm32-unknown-unknown
          profile: minimal
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: -p wasm-client --target wasm32-unknown-unknown
      - uses: actions-rs/cargo@v1
        with:
          command: test
           args: -p wasm-client
